### ISSUE TITLE
Automatic CI build triggering

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-extensions-hosting#1]
Having a little trouble getting AppVeyor to trigger automatically upon `dev` branch changes. May be resolved after some appveyor.yml fixes, but the first build still required manual triggering.

**Comment by nblumhardt** [comment]
The first dev build succeeded; package should show up here soon: https://www.nuget.org/packages/serilog.extensions.hosting

**Comment by andrewlock** [comment]
Looks good to me! The version number is currently set to 2.0.0, as that matches with the _Serilog.AspNetCore_ version (and copy and pasting!) but is that ok or should it be 1.0.0?

**Comment by nblumhardt** [comment]
No strong preferences here :-)

**Comment by gfoidl** [comment]
As a consumer of Serilog v2 version 2.0.0 sounds more aligned to me, so I would start with this version.

1.0.0 would be correct according SemVer, but this hints Serilog v1...

**Comment by ghost** [comment]
Cool, let's leave it at 2.0 then

**Comment by matteocontrini** [comment]
When will the package move to "stable"? :)

**Comment by nblumhardt** [comment]
@matteocontrini at this stage we're usually just looking for confirmation that it works broadly; are you having success with the dev version? #3 is queued up and ready to go, so any feedback would be appreciated.

Just realised that this specific ticket is stale, will close, here. Thanks!

**Comment by matteocontrini** [comment]
No issues so far here, it's been working fine

**Comment by nblumhardt** [comment]
Thanks @matteocontrini :+1:

**Comment by nblumhardt** [comment]
Seems like CI is still unhappy; deleting and re-creating the project now.

**Comment by nblumhardt** [comment]
(On AppVeyor, I should mention :-))

**Comment by nblumhardt** [comment]
Okay, build agent didn't have sufficient permissions to create the CI webhook; fixed now :+1:
