### ISSUE TITLE
Logs not flushing

### ISSUE THREAD

**Issue by adz21c** [serilog/serilog-extensions-hosting#15]
Hi,
I am using the _UsingSerilog_ extension to configure logging in a GenericHostBuilder service, which uses ElasticSearch. However, the logs are not being flushed on service start up errors.

Below is some code to illustrate what I am doing.

A generic base for hosted services that includes logging, just a simple: starting, started, and error wrapper (as best I can see logging isn't provided out the box, please correct me if I am wrong :-)).
```csharp
    public abstract class AbstractHostedService : IHostedService
    {
        private readonly ILogger _logger;
        private readonly string _serviceName;

        protected AbstractHostedService(ILogger logger, string serviceName)
        {
            _logger = logger;
            _serviceName = serviceName;
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            try
            {
                _logger.LogInformation("Starting service {ServiceName}...", _serviceName);

                await DoStartAsync(cancellationToken);

                _logger.LogInformation("Service {ServiceName} started.", _serviceName);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Service {ServiceName} failed to start.", _serviceName);
                throw;
            }
        }

        protected abstract Task DoStartAsync(CancellationToken ct);

        public async Task StopAsync(CancellationToken cancellationToken)
        {
            try
            {
                _logger.LogInformation("Stopping service {ServiceName}...", _serviceName);

                await DoStopAsync(cancellationToken);

                _logger.LogInformation("Stopped {ServiceName} started.", _serviceName);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Service {ServiceName} failed to stop.", _serviceName);
                throw;
            }
        }

        protected abstract Task DoStopAsync(CancellationToken ct);
```

Startup configuration, MyService inherits AbstractHostedService.
```csharp
        static int Main(string[] args)
        {
            try
            {
                return (int)CreateHostBuilder(args).RunAsTopshelfService(s =>
                {
                    // Service config
                });
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return new HostBuilder()
                .ConfigureAppConfiguration((hostingContext, config) => config
                 // Config file setup
                 )
                .ConfigureServices((h, s) => s
                    .AddHostedService<MyService>()
                    // Services setup
                 )
                // ElasticSearch configured using appSettings.json
                .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
                    .ReadFrom.Configuration(hostingContext.Configuration)
                    .WriteTo.ColoredConsole());
        }
```

As you can see I've enclosed the host start in a try/finally that forces a flush. My understanding, having a brief look over the code here, is the flushing should be happening automatically for me. If I don't force a flush then I don't seem to receive any error logs in ElasticSearch (but they do come through in the console logging), so my only solution is the force flush without preserving the static logger. I suppose it could be an indication of a problem with the ES sink, but I figured this seemed like a good starting point.

Am I doing something wrong or is there a problem here?

Thanks,
Adam

**Comment by nblumhardt** [comment]
Thanks for the heads-up!

`UseSerilog()` adds a `SerilogLoggerFactory` to the app's `ServiceCollection`:

https://github.com/serilog/serilog-extensions-hosting/blob/6a8e484efa2575f205d87e70a5527d49a195f769/src/Serilog.Extensions.Hosting/SerilogHostBuilderExtensions.cs#L123

This ends up disposed when the service collection is disposed, and through a chain of calls this ends up calling `Log.CloseAndFlush()` in `SerilogLoggerProvider`:

https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLoggerProvider.cs#L43

The first thing I'd check is that the DI container is being torn down (disposed) when the app exits.

Also, it's worth checking that you're running the latest versions of all the _Serilog.*_ packages, as there have been bugs fixed in this area over time.

Let us know how you go! 👍

**Comment by adz21c** [comment]
I ensured the latest Serilog packages and it had no affect.

I created a disposable class, registered it with the container, and put a breakpoint is the dispose method. If the service starts normally then on shutdown the dispose breakpoint was triggered. However, if there is an exception during hostedservice start up the dispose breakpoint isn't triggered. 

This would imply to me that the container isn't getting cleaned up properly in the event of service start failure. What isn't clear is if this is intended behaviour? I notice on in the read me for this project it indicates the need for a try/finally for "configuration issues", but this I would consider a start up issue. 

> Next, in your application's Program.cs file, configure Serilog first. A try/catch block will ensure any configuration issues are appropriately logged:

Is this intended behaviour or should I be raising an issue with the appropriate .NET team or am I in the right place anyway?

**Comment by adz21c** [comment]
After posting it occurred to me that I had not tried using the builtin RunAsConsoleAsync this whole time. I gave it a try and the container is correctly disposed, even on startup error. This leads me to believe it is actually a bug in the TopShelf host extension I am using, so I am going to close this issue and redirect my focus there.

Thanks for your quick feedback and time.
Adam

**Comment by nblumhardt** [comment]
Interesting - thanks for the follow-up. Does sound like the problem lies elsewhere. Cheers!
