### ISSUE TITLE
Argument ordering on configuration lambda

### ISSUE THREAD

**Issue by ralphhendriks** [serilog/serilog-extensions-hosting#22]
In #20 (still in beta package) a new overload of `UseSerilog()` has been introduced

```csharp
UseSerilog(
    this IHostBuilder builder,
    Action<HostBuilderContext, IServiceProvider, LoggerConfiguration> configureLogger,
    bool preserveStaticLogger = false,
    bool writeToProviders = false)
```

in addition to the already existing (publicly released)

```csharp
UseSerilog(
    this IHostBuilder builder,
    Action<HostBuilderContext, LoggerConfiguration> configureLogger,
    bool preserveStaticLogger = false,
    bool writeToProviders = false)
```

Wouldn't it be more logical to change the ordering of the arguments on the `configureLogging` lambda of the newly added overload to `HostBuilderContext, LoggerConfiguration, IServiceProvider`? That makes refactoring of code just a little easier. I can contribute a PR, but only of course if this aligns with the views of the maintainers.

**Comment by nblumhardt** [comment]
Thanks for the note. I spent some time thinking about this, too, and ended up concluding that `LoggerConfiguration` in the middle position felt arbitrary; the "logic" :-) behind the current argument ordering is (input, input, output), which might or might not make sense in this context. Open to changing it but could be a bikeshed, interested in more opinions 👍

**Comment by ralphhendriks** [comment]
@nblumhardt thanks for the explanation of your rationale. Let's not turn this into a bikeshed indeed. Closing this issue.
