### ISSUE TITLE
UseSerilog inline configuration called multiple times during host initialization. Missing cleanup?

### ISSUE THREAD

**Issue by germanftorres** [serilog/serilog-extensions-hosting#27]
Hi,

During application wiring and startup `UseSerilog` inline configuration may be called multiple times if service registrations need to create a logger instance using a temporary service provider.

```csharp
public static IServiceCollection AddMyService(this IServiceCollection services)
{
    // create a service provider with registered services so far
    var provider = services.BuildServiceProvider();

    // resolve logger
    // This produces a call to UseSerilog((hostingContext, serviceProvider, loggerConfiguration) => {})
    var logger = provider.GetRequiredService<ILogger<MyServiceExtensions>>();

    logger.LogInformation("adding my service with following config...");

    // register whatever needed
    ...
}

```
In this context of logging during service registration and using a file sink, I end up with multiple log files, each one having exactly one message.

```
log20200919.txt
log20200919_001.txt
log20200919_002.txt
```

It seems as the previous existing logger doesn't get property disposed and the file sinks are still holding a lock to the log file. <strike>Calling `Log.CloseAndFlush()` before returning from the inline configuration resolves this issue.</strike>

```csharp
.UseSerilog((hostingContext, serviceProvider, loggerConfiguration) => {
    
    // This doesn't resolve issue either
    // Log.CloseAndFlush();

    loggerConfiguration
        .WriteTo.Console();

    if(hostingContext.HostingEnvironment.IsProduction())
    {
        loggerConfiguration
            .WriteTo.File("Logs/log.txt", rollingInterval: RollingInterval.Day);
    }
})
```
Maybe some cleanup is needed to ensure that the inline configuration doesn't leak resources even if the framewok calls it multiple times.

Thanks

**Comment by nblumhardt** [comment]
Thanks for the note, could be something for us to check out, here.

Personally, I'd try hard to avoid multiple calls to `BuildServiceProvider()` - it seems like a bit of a minefield, to me, with a high probability of introducing subtle bugs.

Any chance that, instead of resolving your logger from the service provider during start-up, you can just create and dispose a temporary Serilog logger?

```csharp
public static IServiceCollection AddMyService(this IServiceCollection services)
{
    // create a service provider with registered services so far
    var provider = services.BuildServiceProvider();

    // resolve logger
    // This produces a call to UseSerilog((hostingContext, serviceProvider, loggerConfiguration) => {})
    using var logger = new LoggerConfiguration()
        .WriteTo.Console()
        .CreateLogger();

    logger.ForContext<MyServiceExtensions>()
        .Information("adding my service with following config...");

    // register whatever needed
    ...
}
```

**Comment by germanftorres** [comment]
Hi, thanks. It seems that the use of BuildServiceProvider is heavily discouraged. Will try to get rid of that pattern and also maybe use a trasient logger for application startup as your recommendation.

Anyway, in the end it would be great to just configure the logger once. If you go the static Log.Logger route, it's very easy to setup but you don't have access to aspnet generic host environment and configuration objects to configure the logger. If you rely on DI with UseSerilog, logging before or during host bootstrapping is also difficult to setup.

**Comment by nblumhardt** [comment]
Thanks for the follow-up; yes, working on those challenges via https://github.com/nblumhardt/serilog-reload :+1:
