### ISSUE TITLE
ReloadableLogger not allowed in netstandard2.0 projects

### ISSUE THREAD

**Issue by dwoldo** [serilog/serilog-extensions-hosting#50]
What is the goal of preventing use of `ReloadableLogger` in netstandard projects ([Serilog.Extensions.Hosting.csproj](https://github.com/serilog/serilog-extensions-hosting/blob/master/src/Serilog.Extensions.Hosting/Serilog.Extensions.Hosting.csproj#L27) and [LoggerConfigurationExtensions.cs](https://github.com/serilog/serilog-extensions-hosting/blob/master/src/Serilog.Extensions.Hosting/LoggerConfigurationExtensions.cs#L15))? I am building a common library that should be reused across dozens of projects to simplify and standardize logging for both [worker service](https://docs.microsoft.com/en-us/dotnet/core/extensions/workers) and ASP.NET Core apps.

To work around this I am forced to target a dotnet [TFM ](https://docs.microsoft.com/en-us/dotnet/standard/frameworks )which causes compatibility issues where consuming projects use older [TFM](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)s.

**Comment by nblumhardt** [comment]
Hi! `ReloadableLogger` relies on default interface implementations, which aren't available on older CLRs (aren't supported on .NET Framework at all). HTH!

**Comment by dwoldo** [comment]
Certainly does, thank you @nblumhardt .
