### ISSUE TITLE
Missing CreateBootstrapLogger in .net framework 4.8

### ISSUE THREAD

**Issue by menaheme** [serilog/serilog-extensions-hosting#61]
hello 

I cant seem to find the create bootsrap logger method when working with. Net Framework

**Comment by nblumhardt** [comment]
Hi! This API isn't supported on .NET Framework or early versions of .NET Core - it relies on default interface implementations, which the CLR doesn't support on those platforms. We don't have any plans to try back-porting it at this point. HTH!

**Comment by menaheme** [comment]
So how do i log failures in the host init?

**Comment by nblumhardt** [comment]
Hi! It's possible to create a separate logger at start-up, just using `CreateLogger()`, that can separately log startup errors:

```csharp
using var startupLog = new LoggerConfiguration().WriteTo.Console().CreateLogger();
try
{
    // Start-up, including `UseSerilog(callback)`
}
catch (Exception ex)
{
    startupLog.Error(ex, "Failed to start");
}
```

HTH,
Nick

**Comment by menaheme** [comment]
Of course, Thank you
