### ISSUE TITLE
Problem targeting Microsoft.Extensions.Hosting.Abstractions 2.1.1

### ISSUE THREAD

**Issue by kakins** [serilog/serilog-extensions-hosting#7]
I'd love to use these extensions for my app, but I get this runtime issue when targeting v2.1.1 of Microsoft.Extensions.Hosting.Abstractions:

System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

**Comment by andrewlock** [comment]
Hi, I've just tried to reproduce this, but I can't find any issues. I updated all the packages [in the sample](https://github.com/serilog/serilog-extensions-hosting/blob/dev/samples/SimpleServiceSample/SimpleServiceSample.csproj) to target v2.1.1, and tried adding a reference to Microsoft.Extensions.Hosting.Abstractions as well, but it builds and runs without issue. 

Can you share a project that reproduces the problem?

**Comment by kakins** [comment]
So this seemed to fix the problem:
https://github.com/aspnet/Hosting/issues/926#issuecomment-276802099

I believe the cause is that I have a .NET 4.7.1 project which targets v2.1.1 of the Microsoft.Extensions* packages, and Serilog targets v2.1.0.  

In this scenario I have to enable Automatic Binding Redirection, as described here:
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection

Thanks for your help!
