### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple

### ISSUE THREAD

**Issue by baihao** [serilog/serilog-extensions-hosting#92]
Hi team,

 Is there a plan to include the `PrivacyInfo.xcprivacy` manifest as required by Apple? ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Hao

**Comment by bartelink** [comment]
Let's have just one instance of these issues please. (Closing this one as I can't off the top of my head figure out how/why you'd be `.Hosting` anything on an Apple platform)

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-settings-configuration/issues/424
